language: android
jdk: oraclejdk8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - g++-6
env:
  global:
    - ANDROID_API_LEVEL=23
    - ANDROID_BUILD_TOOLS_VERSION=25.0.0

android:
  components:
    - cmake
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-google_apis-21


before_install:
    - chmod +x gradlew
    - chmod +x cdep

install:
  - wget --no-check-certificate https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip -O android-ndk-r13b-linux-x86_64.zip
  - unzip android-ndk-r13b-linux-x86_64.zip > android-ndk-r13b-linux-x86_64.uncompress-log 2>&1
  - export ANDROID_NDK_HOME=$PWD/android-ndk-r13b
  - wget https://github.com/Commit451/android-cmake-installer/releases/download/1.1.0/install-cmake.sh
  - chmod +x install-cmake.sh
  - "./install-cmake.sh"
  - find ${ANDROID_HOME}cmake/*/bin/cmake

script:
  - ./cdep
  - ./gradlew assemble

  - android list targets

  - echo no | android create avd --force -n testemulator -t "android-21" --abi armeabi-v7a
  - echo 'vm.heapSize=512' >> ~/.android/avd/testemulator.ini
  - echo 'hw.ramSize=1024' >> ~/.android/avd/testemulator.ini
  - cat ~/.android/avd/testemulator.ini

  - emulator -avd testemulator -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - ./gradlew connectedAndroidTest
